CXX=$(shell wx-config --cxx)
CXXFLAGS+=-Wall -I/usr/local/include -Iinclude -Wfatal-errors
CXXFLAGS+=-stdlib=libc++ -std=c++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.13

CXXFLAGS+=$(shell wx-config  --cppflags core,base) 
#CXXFLAGS+=-I/usr/include/machine # we need this for <endian.h>?!?!
CXXFLAGS+=-g -O0 # debug me

LIBS+=$(shell wx-config --libs) -lscrypt -lmbedtls -lmbedcrypto -lmbedx509
LDFLAGS=$(CXXFLAGS)
LDFLAGS+=-stdlib=libc++
TARGET=passmate
SRC=$(wildcard *.cpp)
#SRC=Record.cpp Storage.cpp MainWindow.cpp Application.cpp ScryptEnc.cpp
EECHO=echo
.PHONY: all
all: $(TARGET)
$(TARGET): $(SRC:.cpp=.o)
	@$(EECHO) " \033[34m[LD]\033[0m\t$@"
	@$(CXX) $(LDFLAGS) -o $@ $^ $(LIBS)
%.o: %.cpp
	@$(EECHO) " \033[33m[CC]\033[0m\t$@"
	@$(CXX) $(CXXFLAGS) -c $< -o $@
%.d: %.cpp
	@$(EECHO) " \033[35m[DP]\033[0m\t$@"
	@set -o errexit; rm -f $@; \
	$(CXX) $(CXXFLAGS) -M $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$
-include $(SRC:.cpp=.d)
.PHONY: clean
clean:
	@$(EECHO) " \033[31m[RM]\033[0m"
	@rm -f $(TARGET) $(SRC:.cpp=.o) $(SRC:.cpp=.d)
# disables implicit rules:
.SUFFIXES:
